export const FETCH_ALL_REQUEST = 'FETCH_ALL_REQUEST'
export const FETCH_ALL_SUCCESS = 'FETCH_ALL_SUCCESS'
export const FETCH_ALL_ERROR = 'FETCH_ALL_ERROR'

export const CREATE_REQUEST = 'CREATE_REQUEST'
export const CREATE_SUCCESS = 'CREATE_SUCCESS'
export const CREATE_ERROR = 'CREATE_ERROR'

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR'